#encoding:utf-8
import os
from django.contrib.gis.utils import LayerMapping

from models import Institutos_Educativos

institutos_educativos_mapping = {
    'ie_id' : 'id',
    'ie_canton_cod' : 'canton_cod',
    'ie_canton' : 'canton',
    'ie_parroquia' : 'parroquia',
    'ie_codigo_distrito' : 'codigo_dis',
    'ie_t_sede' : 't_sede',
    'ie_circuito_cod' : 'circuito_c',
    'ie_casos_exce' : 'casos_exce',
    'ie_institucion' : 'institucio',
    'ie_ute' : 'ute',
    'ie_unidad_eje' : 'unidad_eje',
    'ie_codigo_ue' : 'codigo_ue',
    'ie_sin_nombre' : 'sin_nombre',
    'ie_region' : 'region',
    'ie_sostenimiento' : 'sostenimie',
    'ie_regimen' : 'regimen',
    'ie_jurisdiccion' : 'jurisdicci',
    'ie_tipo_educacion' : 'tipo_educa',
    'ie_escolarizacion' : 'escolariza',
    'ie_modalidad' : 'modalidad',
    'ie_jornada' : 'jornada',
    'ie_genero_ofertado' : 'genero_ofe',
    'ie_nivel_educacion' : 'nivel_educ',
    'ie_administracion' : 'administra',
    'ie_financiamiento' : 'financiami',
    'ie_zona_institucion' : 'zona_insti',
    'ie_zona_inec' : 'zona_inec',
    'ie_forma_gestion' : 'forma_gest',
    'ie_etnia' : 'etnia',
    'ie_nacionalidad' : 'nacionalid',
    'ie_pueblo' : 'pueblo',
    'ie_docentes' : 'docentes',
    'ie_administrativo' : 'administ_1',
    'ie_anio3' : 'anio3',
    'ie_anio4' : 'anio4',
    'ie_grado1' : 'grado1',
    'ie_grado2' : 'grado2',
    'ie_grado3' : 'grado3',
    'ie_grado4' : 'grado4',
    'ie_grado5' : 'grado5',
    'ie_grado6' : 'grado6',
    'ie_grado7' : 'grado7',
    'ie_grado8' : 'grado8',
    'ie_grado9' : 'grado9',
    'ie_grado10' : 'grado10',
    'ie_curso1' : 'curso1',
    'ie_curso2' : 'curso2',
    'ie_curso3' : 'curso3',
    'ie_alfabetiza' : 'alfabetiza',
    'ie_formacion' : 'formacion_',
    'ie_formacion1' : 'formacion1',
    'ie_no_escolar' : 'no_escolar',
    'ie_otros' : 'otros',
    'ie_total_estu' : 'total_estu',
    'ie_total_cons' : 'total_cons',
    'ie_estudiante' : 'estudiante',
    'ie_estudian_1' : 'estudian_1',
    'ie_tipo_especialidad' : 'tipo_espec',
    'ie_especialidades' : 'especialid',
    'ie_discapacidad' : 'discapacid',
    'ie_unidocente' : 'unidocente',
    'ie_acceso' : 'acceso',
    'ie_tipo_de_calle' : 'tipo_de_ca',
    'ie_energia_planta' : 'energia_pl',
    'ie_red_publica' : 'red_public',
    'ie_energia_solar' : 'energia_so',
    'ie_internet' : 'internet',
    'ie_biblioteca' : 'biblioteca',
    'ie_computadoras' : 'computador',
    'ie_terreno' : 'terreno',
    'ie_construccion' : 'construcci',
    'ie_aulam2' : 'aulam2',
    'ie_num_pupitres' : 'num_pupitr',
    'ie_disenio' : 'disenio',
    'ie_cerramiento' : 'cerramient',
    'ie_tenencia' : 'tenencia',
    'ie_riesgo_primario' : 'riesgo_pri',
    'ie_riesgo_secundario' : 'riesgo_sec',
    'ie_inundacion' : 'inundacion',
    'ie_beneficios' : 'beneficios',
    'ie_comparte1' : 'comparte1',
    'ie_comparte2' : 'comparte2',
    'ie_comparte3' : 'comparte3',
    'ie_comparte4' : 'comparte4',
    'ie_laboratorios' : 'laboratori',
    'ie_talleres' : 'talleres',
    'ie_x' : 'X',
    'ie_y' : 'Y',
    'geom' : 'MULTIPOINT',
}

institutos_educativos_shp = os.path.abspath( os.path.join( os.path.dirname(__file__), 'data/instituciones_educativas.shp' ) )

def run(verbose=True):
	lm = LayerMapping(Institutos_Educativos, institutos_educativos_shp, institutos_educativos_mapping, transform=False, encoding='utf-8')
	lm.save(strict=True, verbose=verbose)
